CUDA_VISIBLE_DEVICES=0 python main.py \
  --synthetic_train_data_dir '/home/liming/ShareWindows/Free_zome/Self-labeled_data/obj_label/crop' \
  --test_data_dir '/home/liming/ShareWindows/Free_zome/Self-labeled_data/obj_label/crop_test' \
  --batch_size 4 \
  --workers 8 \
  --height 128 \
  --width 128 \
  --logs_dir '/home/liming/Desktop/Program/simple-classification-model/Frame_work/logs/test'\
  --real_logs_dir '/home/liming/Desktop/Program/simple-classification-model/Frame_work' \
  --lr 0.1 \
  --epochs 10